import "./globals.css";

export const metadata={
  title: {
    absolute: "",
    default: "Next.js _ Codevolution",
    template: "%s | Codevolution"

  },
  description: "Generated by Next.js"
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col justify-between h-screen w-full">
        <header>
          <p>headers</p>
        </header>
        <div>
          {children}
        </div>
        <footer>
          This is my footer
        </footer>
      </body>
    </html>
  );
}

